# Generated by Django 4.1.3 on 2022-11-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='xyz@gmail.com', max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
